export const SITE_TITLE = 'Alejandro Escobar'
export const SITE_TAGLINE = '🚀 De Emprendedor a Empresario 🚀'
export const SITE_DESCRIPTION =
  'Coaching para emprendedores 🌟Transforma tu negocio ¡YA! 🌟 Sesiones 1:1 totalmente individualizadas y seguimiento continuo'
export const SITE_URL = 'https://alejandroescobar.com'
export const SITE_LANG = 'es'
export const SITE_IMAGE = `${SITE_URL}/handshake.jpg`
export const SITE_ICONO = '/src/assets/svg/degLogo-01.svg'
export const SITE_FAVICON = '/favicon.svg'
export const SITE_TWITTER = '@alejandroescobr'
export const SITE_FACEBOOK = 'alejandroescobar'
export const SITE_INSTAGRAM = 'alejandroescobar'
export const SITE_LINKEDIN = 'alejandroescobar'
export const SITE_EMAIL = ''
export const SITE_PHONE = ''
export const SITE_ADDRESS = ''
